Repository PDA-Final-Project-Team1/FE, pull requests merged in 2025-03, with the labels that each got.

#87 Refactor : useSSE 리팩토링
  src/hooks/useSSE.js
Labels: enhancement

#98 Fix: 로딩페이지 해결
  src/Domain/Town/pages/TownMainPage.jsx
Labels: bug

#100 Refactor: 친구로직 이슈 해결
  src/Domain/Town/pages/FriendPage.jsx
Labels: bug

#105 Feat: 거래 내역 필터 및 페이징 추가
  src/Domain/User/components/MyTrade.jsx
Labels: enhancement

#107 Develop
  src/Domain/Quiz/pages/QuizDonePage.jsx
  src/Domain/Town/components/GaugeBar.jsx
  src/Domain/Town/components/PetAcqModal.jsx
  src/Domain/Town/components/StockAcqModal.jsx
  src/Domain/Town/pages/EggListPage.jsx
  src/Domain/Town/pages/FriendPage.jsx
  src/Domain/Town/pages/TownMainPage.jsx
  src/Domain/Trade/components/BuyFailureModal.jsx
  src/Domain/Trade/components/SearchCompany.jsx
  src/Domain/Trade/components/SellFailureModal.jsx
  src/Domain/Trade/components/StockBottom.jsx
  src/Domain/Trade/components/StockInfo.jsx
  src/Domain/Trade/components/TradeHeader.jsx
  src/Domain/Trade/components/UnholdSuccessModal.jsx
  src/Domain/Trade/pages/StockPage.jsx
  src/Domain/Trade/pages/TradeMainPage.jsx
  src/Domain/User/components/MyAccount.jsx
  src/Domain/User/components/MyHeld.jsx
  src/Domain/User/components/MyInterested.jsx
  src/Domain/User/components/MyTable.jsx
  src/Domain/User/components/MyTrade.jsx
  src/hooks/useSSE.js
Labels: enhancement

#111 Fix: 거래 내역이 없을 때 첫 페이지 번호 0번으로 수정
  src/Domain/User/components/MyTrade.jsx
Labels: bug

#114 Fix: 거래 알림 수정
  src/common/pages/Alert.jsx
Labels: enhancement

#119 Refactor/#118 css 버그 수정
  src/App.jsx
  src/Domain/Quiz/pages/ChatbotPage.jsx
  src/Domain/Quiz/pages/QuizDonePage.jsx
  src/Domain/Quiz/pages/QuizLevelPage.jsx
  src/Domain/Quiz/pages/TodayQuizPage.jsx
  src/Domain/Town/components/LoadingScreen.jsx
  src/Domain/Town/pages/DogamPage.jsx
  src/Domain/Town/pages/DrawPage.jsx
  src/Domain/Town/pages/EggListPage.jsx
  src/Domain/Town/pages/FriendPage.jsx
  src/Domain/Town/pages/FriendTownPage.jsx
  src/Domain/Town/pages/TownMainPage.jsx
  src/Domain/Trade/components/StockBottom.jsx
  src/Domain/Trade/pages/OrderBookPage.jsx
  src/Domain/Trade/pages/StockPage.jsx
  src/Domain/Trade/pages/StockTradePage.jsx
  src/Domain/Trade/pages/TradeMainPage.jsx
  src/Domain/User/components/MyTrade.jsx
  src/Domain/User/pages/MyMainPage.jsx
  src/Domain/User/pages/MyStockPage.jsx
  src/Domain/User/pages/MyTradePage.jsx
  src/common/components/Footer.jsx
  src/common/components/LandingCharacters.jsx
  src/common/pages/LogInPage.jsx
  src/common/pages/SignUpPage.jsx
  src/index.css
Labels: bug, enhancement

#122 Develop
  package-lock.json
  package.json
  src/Domain/Trade/components/OrderBook.jsx
Labels: bug

#123 Refactor: css 버그 수정
  src/Domain/Town/pages/DrawPage.jsx
  src/Domain/Trade/components/OrderCheckModal.jsx
  src/Domain/Trade/components/StockBottom.jsx
  src/Domain/Trade/components/TradeSuccessModal.jsx
  src/Domain/Trade/pages/StockTradePage.jsx
Labels: bug

#126 Refactor: css 버그 수정
  src/App.jsx
  src/Domain/Quiz/pages/ChatbotPage.jsx
  src/Domain/Trade/components/StockBottom.jsx
  src/common/components/LandingCharacters.jsx
Labels: bug

#139 Fix: 친구 기능 버그 해결
  src/Domain/Town/components/SearchFriend.jsx
  src/Domain/Town/pages/FriendPage.jsx
Labels: bug
